### ISSUE TITLE
OmicsMetaData: an R-package for interoperable and re-usable biodiversity 'omics (meta)data

### ISSUE THREAD

**Issue by msweetlove** [ropensci/software-review#471]
Submitting Author Name: Maxime Sweetlove
Submitting Author Github Handle: @msweetlove
Other Package Authors Github handles: @ymgan, @Antonarctica
Repository:  https://github.com/biodiversity-aq/OmicsMetaData
Version submitted: 0.0.1
Submission type: Standard
Editor: @jooolia
Reviewers: @ginberg, @cpalmer718

Due date for @ginberg: 2021-12-26
Due date for @cpalmer718: 2022-02-19
Archive: TBD
Version accepted: TBD

---

-   Paste the full DESCRIPTION file inside a code block below:

```
Package: OmicsMetaData
Title: OmicsMetaData: an R-package for interoperable and re-usable biodiversity 'omics (meta)data.
Version: 0.0.1
Authors@R: 
	person("Maxime",
		"Sweetlove",
		role = c("aut", "cre"),
		email = "msweetlove@naturalsciences.be")
Description: 
		OmicsMetaData: tools to re-use biodiversity 'omics datasets or standardize them to make them globally interoperable
License: GNU General Public License v3 (GLP-3.0) https://www.gnu.org/licenses/gpl-3.0.en.html
Encoding: UTF-8
LazyData: true
Imports:
    worrms (>=0.4.2),
    stringr (>=1.4.0),
    Orcs (>=1.2.1),
    xml2 (>=1.3.2),
    reshape2 (>=1.4.4)
Depends:
    tidyr (>=1.1.3),
    RecordLinkage(>=0.4-12.1),
    mapview (>=2.10.0),
    rgbif (>=3.6.0),
    R (>= 4.0.1)
RoxygenNote: 7.1.1
Suggests: 
    testthat (>=2.3.2),
    roxygen2 (>=7.1.1),
    devtools (>=2.3.0)
```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under:

	- [x] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
data retrieval: The OmicsMetaData package allows users to download nucleotide sequences from INSDC alongside any associated metadata linked to the sequences, based on a BioProject identification number.

data munging: The OmicsMetaData package provides tools to format biodiversity 'omics metadata following the widely used data standards MIxS (for 'Omics data) and DarwinCore (for biodiversity data). Standardizing datasets makes them much more easily interoperable between researchers and institutions and across time, and makes it easier for users to archive the metadata alongside the sequences on the INSDC databases.

-   Who is the target audience and what are scientific applications of this package?
Scientists that work with biodiversity 'omics datasets on a daily basis, and have a need to standardize the data to exchange it between colleagues or archive it online after the end of a project, or if they want to expand their dataset with online openly available sequence data.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)? 
At present I am not aware of any such packages.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
Not applicable.

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.
Not applicable.

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by msweetlove** [comment]
@mpadge the spaces have been added to the DESCRIPTION file in the repo: https://github.com/biodiversity-aq/OmicsMetaData

**Comment by jooolia** [comment]
@ropensci-review-bot add @orchid00 to reviewers

**Comment by jooolia** [comment]
Hello @orchid00 ! thanks for agreeing to review. I am still looking for a second reviewer and we did agree that your review would have a later due date of December 15th (however if it is done earlier that is great).

**Comment by jooolia** [comment]
Dear @msweetlove ,
I am still looking for a second reviewer. Thanks, Julai

**Comment by jooolia** [comment]
@ropensci-review-bot add @ginberg to reviewers

**Comment by jooolia** [comment]
Dear @ginberg thanks for agreeing to review!

**Comment by ginberg** [comment]
## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [x] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [x] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples:** (that run successfully locally) for all exported functions
- [x] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [x] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 4

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

README 
- contains a typo: 'lisence' instead of license
- styling: some (sub)titles are not showing up as subtitles since there is no space between the hashtags and the title

Check:
- devtools is listed twice in Suggests section in DESCRIPTION

Vignettes:
- styling: some (sub)titles are not showing up as subtitles since there is no space between the hashtags and the title

Automated tests:
- The overall test coverage is good (78.91%). There are 20 warnings when running all tests, could you fix these?

Packaging guidelines:
- rOpenSci recommends a package name in lowercase in their [guidelines](https://devguide.ropensci.org/building.html), could you change that?

**Comment by jooolia** [comment]
Thanks very much @ginberg  for the review. (sorry for my slow response)

**Comment by jooolia** [comment]
Hi @orchid00, do you think it will be possible to submit your review soon? Thanks, Julia

**Comment by orchid00** [comment]
I'm sorry, I was not able to do the review, I prefer to step out. 
I was on leave first, then I got ill. Now back to too many things to accomodate for.

**Comment by jooolia** [comment]
Hi @orchid00,
Thanks for letting me know. Hope you are feeling better and wishing you the best. 

I will look for another reviewer @msweetlove. Thanks!

**Comment by jooolia** [comment]
@ropensci-review-bot add @cpalmer718 to reviewers

**Comment by jooolia** [comment]
Dear @cpalmer718, thank you for agreeing to review! The due date for your review is 2022-02-19.  Please refer to our [reviewer guide](https://devguide.ropensci.org/reviewerguide.html). If you have any questions feel free to ask here or via email. 
Thanks, Julia

**Comment by cpalmer718** [comment]
Hi @msweetlove @jooolia please see below for my review. I've added commentary at the bottom to explain some of it. I'm trying to return this early because I wasn't able to clearly evaluate parts of the package on my system, so we may need to iterate a bit.

## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [x] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [ ] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [ ] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [x] **Function Documentation:** for all exported functions
- [x] **Examples:** (that run successfully locally) for all exported functions
- [x] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [ ] **Installation:** Installation succeeds as documented.
- [x] **Functionality:** Any functional claims of the software been confirmed.
- [x] **Performance:** Any performance claims of the software been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 10

- [x] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

---

### Review Comments

#### Installation
  - Windows
    - Based on the ropensci specs, I'm assuming this is intended to work on Windows, but I guess I don't know for certain. In any case, my primary test system happened to be Windows 10, but the package example under "Brief demonstration usage" does not work on Windows due to hard-coded use of wget. This also seems to break the testthat tests. It seems like this package was developed on OSX; was this tested on Windows or Linux? I recommend replacing "wget" with "auto" to allow R to figure it out.
    - Assigning encoding as "UTF-8" without conversion fails on Windows 10 (degree symbol is declared invalid UTF-8, tests fail). this is obviously very likely platform dependent. passing character vector through appropriate sanitizer `enc2utf8` fixes the problem.
    - A vignette example in "Retrieving online data" fails on Windows with the error `Error in download.file(ftp_url, destfile = file.path(destination.path,  : scheme not supported in URL 'ftp.sra.ebi.ac.uk/vol1/fastq/SRR298/004/SRR2980684/SRR2980684_1.fastq.gz'.` Apparently the "auto" setting is causing Windows to choose a download method that doesn't support ftp. This is seemingly resolved by setting the method parameter in `download.file` to "libcurl" as it is available on my system. I'd recommend going through the `download.file` documentation and coming up with a logic chain that hopefully guarantees the download will succeed for any system (which may involve requiring non-R system dependencies), or otherwise exposing the method parameter to the user so they can override the system's choice without editing the library's source code.
  - OSX/Linux
    - After having problems with Windows, I tried installing on OSX and Linux, and had different issues. I tried installing in clean conda environments and ran up against a number of system dependencies that failed. Can you please try out clean installations on those systems and document system dependencies that may be required (e.g. `libudunits2`, `gdal`, etc.)?
#### Documentation
  - README.md has various issues with markdown syntax that are interfering with legibility: code blocks formatted as R, spaces after '#' characters in headers, etc.
  - The "Settings" page for NCBI doesn't have a clear link once you click to their site; it might be helpful to provide clearer instructions about how to get to the right page.
  - The way the API key is ingested in the package, it seems like it's encouraging users to paste it into scripts, which represents a kind of security vulnerability. It would be nice to instruct users how they might better secure their API key for use in R (for example placing it in .Renviron or using a more formal handling mechanism.
#### Vignettes
  - Similar to README.md, working on improving the markdown syntax and presentation could really help the legibility of the vignettes. They're hard to get through at the moment.
  - Please add `author: "{name}"` tags to YAML headers of vignette .Rmd files
  - Be sure to change links to other vignettes from within the vignettes to point to .html files instead of .Rmd source files. It would also be helpful to link a table of contents at the top of each vignette, or something like that, given the number of vignettes.
  - `workingDir` is defined in `Metadata_standardization` but then not used, and in the final statement `write.MIxS` function emits relative to working directory
  - In `Retrieving online data`, the example in block `download_sequences` emits the warning `the metadata will be retruned to the Console If you did assign the output of this function to an R-object (using "<-"): better abort and restart now`; since the result is assigned to a variable in the vignette example, this is really confusing as a new user.
  - It seems that no vignette documents anything about DarwinCore content in the library, unless I've missed it somehow.
  - I think, as a general comment, it's hard to get from the vignettes what I'm really looking for as a new user, which is an end-to-end example of what the intended use case is for the package. I think this is in part due to how the vignettes are fragmented, and also that for most of the vignettes the code is not executable as-is. Though it's hard, this experience might be substantially improved by consolidating the vignettes into end-to-end walkthroughs of how you envision the user directly interacting with a dataset, with every step of data management and adjustment provided with a runnable example, and maybe some tables showing the expected data frame contents or similar. This would also possibly provide an opportunity to include DarwinCore content in the vignettes.
#### General repo comments:
  - The license status of the project is unclear. Top level README.md says GPL3 (please be sure to correct typo). However, source files and codedata.json all say CC-0. Please either:
    - harmonize this license selection across all files, and for good measure add license declarations in the header of all source files; or
    - explain in top-level README.md the license status of the project so it's clear
  - R history and data hidden files, and Mac tracker files (`.DS_Store`), should be removed from the repo. The appropriate file patterns should be added to `.gitignore` at top level to prevent their addition to the repo.
  - The convention for default branch naming has changed (see [here](https://github.com/github/renaming)). Please consider renaming the default branch from `master` to `main` or `default` as preferred.
  - `R/sysdata.rda` has something called "MarsLib" in it; is that expected to be there? It seems like several data structures are being loaded directly from saved data files, which are provided as jagged data frames in the package namespace. It works, but it's somewhat unwieldy to work with. It would be nice to have some of the prestock library content available within the library as YAML files or something. Regardless, it really seems like the jagged data frames should be rather lists of vectors, so that when the user accesses one of the shorter vectors, they don't accidentally end up using the many empty string entries at the end of the vector.
#### Style/packaging:
  - The package would really benefit from passes through `styler` and `lintr`. In particular:
    - the cyclomatic complexity is really high for some functions, which makes it very challenging to actually test them.
    - variable and function naming is a bit messy. the combination of camel and dotted snake and all-caps and other styles in the same names at times makes it very difficult to read. the ropensci docs recommend snake_case.
  - Some of the automated checks recommend avoiding `sapply` and some other similar things, and I think that would be good. In particular, there are some statements (e.g. `unlist(unname(sapply(paste))))` that I think could be made much more straightforward by using, for example, paste's vectorized behavior. This doesn't seem to cause any bugs that I've noticed, but it makes it difficult to read and maintain, and depending on the size of your input datasets, some of the for loops might cause some issues. I don't think it really will cause performance degradation at realistic dataset sizes, but it would just make things a lot cleaner and consistent with packaging best practices.
#### Tests:
  - The tests didn't catch some of the issues I had with the package on Windows, so they really could use expansion.
  - Some of the tests technically cover the functions but don't then, for example, check the format of the file emitted by the tested function. I strongly encourage increasing test coverage and thoroughness if you can.

Thank you for inviting me to review! In particular with the Windows system issues, I'd really enjoy taking another look once things are working on the platform.

**Comment by jooolia** [comment]
Dear @msweetlove, have you had time to look at the reviews? Do you know when you will have time to respond?
Thanks, Julia

**Comment by jooolia** [comment]
Email sent to author at naturalsciences.be address.

**Comment by jooolia** [comment]
Email bounced. Tried an address @ vlaanderen.be

**Comment by jooolia** [comment]
Dear @ginberg  and @cpalmer718,
Thank you very much for your reviews. We appreciate the time and care you put into them. The author has switched jobs and cannot continue with the development of this package and unfortunately there is no-one at his former workplace who can carry on with the work so the package development will be stopped. This means that we will close this review now. Please let me know how many hours you each spent reviewing (you can estimate if you can't exactly remember as it was quite some time ago) and we can log this in our reviewer database. 

Thanks again for your help and input,
Julia

**Comment by ginberg** [comment]
@jooolia okay, that's too bad. I spend around 4h and @cpalmer718 seems to have spend 10h (see the review)

**Comment by jooolia** [comment]
Thanks @ginberg! Yes somehow I missed both of your hours. :dizzy_face: thanks for pointing out that the info was already there!

**Comment by cpalmer718** [comment]
@jooolia I'm sorry to hear it, but thanks for inviting me regardless. Yes, that was about the number of hours I spent, thanks @ginberg
